### ISSUE TITLE
请问输出到2K显示器，显示效果与1080p相比是否有很大的提升？另外，如果使用9400F外加A卡的话，能不能通过hdmi完美输出4k或2k？

### ISSUE THREAD

**Issue by zaifoo** [creatorlewis/Hackintosh-ASRock-Deskmini-H310-COM#1]

**Comment by shareur** [comment]
1. 从观感上来看还是挺明显的,2K 确实要比 1080P更细腻一些,
在 2K上播放 1080p的视频:
a.)首先使用原画大小播放,是不可能占满全屏的,这就说明同等尺寸的屏幕,相同面积下,像素点 2K 密度大于1080P,显示效果自然是有区别的.
b)其次,1080P的视频放大全屏观看,就看出其中的区别,颗粒感还是比较明显的.
以上两点的比较建立在同等尺寸屏幕下,2K 与 1080P的对比.
从个人体验来讲,我觉得 1080P与 24 寸及以下的屏幕更配,2K与 27 寸的屏幕更配.
另外,我的游戏主力机用的是 24 寸1080P 144HZ的.
2. 建议你查询搜索其他人的方案,我没有试过 9400F 的组合.倒是之前在主力机AMD 平台:2700X+RX580试过黑苹果,显示没有问题,但是其他问题一大堆.
以上.
